name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Install cargo-near
        run: cargo install cargo-near
          
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Check formatting
        run: cargo fmt --all -- --check
        
      - name: Build NEAR contracts
        run: |
          cd crates/oracle-contract && cargo near build --no-docker
          cd ../reclaim-gpt-contract && cargo near build --no-docker
        
      - name: Check with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        
      - name: Build all crates
        run: cargo build --all-features
        
      - name: Run tests
        run: cargo test --all -- --test-threads=1
